CREATE TABLE IF NOT EXISTS users (
    id                      UUID            PRIMARY KEY,
    "firstName"             VARCHAR(255)    NOT NULL,
    "lastName"              VARCHAR(255)    NOT NULL,
    email                   VARCHAR(255)    NOT NULL UNIQUE,
    password                TEXT,
    "isVerified"            BOOLEAN         NOT NULL DEFAULT FALSE,
    "verifiedAt"            TIMESTAMPTZ,
    "isActive"              BOOLEAN         NOT NULL DEFAULT TRUE,
    "isBlocked"             BOOLEAN         NOT NULL DEFAULT FALSE,
    "isFirstTimeLogin"      BOOLEAN         NOT NULL DEFAULT TRUE,
    role                    "enum_users_role"           NOT NULL,
    country                 VARCHAR(255),
    "phoneNumber"           VARCHAR(255),
    "noOfSubscriptions"     INTEGER         DEFAULT 0,
    "deletedAt"             TIMESTAMPTZ,
    "profilePicture"        VARCHAR(255),
    bio                     TEXT,
    "dateOfBirth"           TIMESTAMPTZ,
    address                 TEXT,
    "socialLinks"           JSON,
    preferences             JSON,
    "lastLoginAt"           TIMESTAMPTZ,
    "timeZone"              VARCHAR(255),
    "lastPasswordChangeAt"  TIMESTAMPTZ,
    "twoFactorEnabled"      BOOLEAN         DEFAULT FALSE,
    "securityQuestions"     JSON,
    "registerMethod"        "enum_users_registerMethod" NOT NULL,
    "googleAccessToken"     TEXT,
    "googleRefreshToken"    TEXT,
    "accessToken"           TEXT,
    "refreshToken"          TEXT,
    "createdAt"             TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    "updatedAt"             TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);