declare const _default: {
    PAYMENT_SERVICE_ROUTE: string | undefined;
    STRIPE_WEBHOOK_SECRET: string | undefined;
    STRIPE_SUCCESS_URL: string | undefined;
    STRIPE_FAILURE_URL: string | undefined;
    STRIPE_PUBLISHABLE_KEY: string | undefined;
    STRIPE_SECRET_KEY: string | undefined;
    STRIPE_BASE_URL: string | undefined;
    MONTHLY_SUBSCRIPTION_PRICE_ID: string | undefined;
    ANNUAL_SUBSCRIPTION_PRICE_ID: string | undefined;
    LIFTIME_SUBSCRIPTION_PRICE_ID: string | undefined;
    PAYMENT_SERVICE_PORT: string | undefined;
    FOUNDERS_LIST_SERVICE_SERVER_PORT: string | undefined;
    GOOGLE_API_KEY: string | undefined;
    GOOGLE_CLIENT_ID: string | undefined;
    GOOGLE_CLIENT_SECRET: string | undefined;
    USERS_PORT: string | undefined;
    CLOUDINARY_CLOUD_NAME: string | undefined;
    CLOUDINARY_API_KEY: string | undefined;
    CLOUDINARY_API_SECRET: string | undefined;
    OPENAI_API_KEY: string | undefined;
    PRONUNCIATION_SERVICE_PORT: string | undefined;
    NOTIFICATION_SERVICE_PORT: string | undefined;
    EDEDUN_PORT: string | undefined;
    LESSON_SERVICE_PORT: string | undefined;
    FOUNDERS_LIST_DB: string;
    USERS_SERVICE_DB: string;
    GOOGLE_REGISTER_CALLBACK_URL: string;
    GOOGLE_LOGIN_CALLBACK_URL: string;
    FRONTEND_URL: string;
    PASSWORD_RESET_URL: string;
    GOOGLE_AUTH_FAILURE_URL: string;
    LOCAL_FOUNDERS_LIST_URL: string;
    NOTIFICATION_SERVICE_ROUTE: string;
    APP_JWT_SECRET: string;
    EDEDUN_APP_SECRET: string;
    EDEDUN_SMTP_USER_NAME: string;
    EDEDUN_SMTP_PASSWORD: string;
    EDEDUN_CLOUDINARY_NAME: string;
    EDEDUN_CLOUDINARY_API_KEY: string;
    EDEDUN_CLOUDINARY_API_SECRET: string;
    EDEDUN_DB: string;
    YORUBA_LANGUAGE_ID: string;
};
export default _default;
