import dotenv from 'dotenv'

dotenv.config()

const {
    USERS_SERVICE_DEV_DB,
    FOUNDERS_LIST_DEV_DB,
    DEV_DEMO_GOOGLE_REGISTER_CALLBACK_URL,
    DEV_DEMO_GOOGLE_LOGIN_CALLBACK_URL,
    DEV_FRONTEND_URL,
    DEV_PASSWORD_RESET_URL,
    GOOGLE_AUTH_FAILURE_URL,
    LOCAL_FOUNDERS_LIST_URL,
    NOTIFICATION_SERVICE_ROUTE,
    APP_JWT_SECRET
} = process.env


console.log('Running in development mode')

export default {
    FOUNDERS_LIST_DB: FOUNDERS_LIST_DEV_DB!,
    USERS_SERVICE_DB: USERS_SERVICE_DEV_DB!,
    GOOGLE_REGISTER_CALLBACK_URL: DEV_DEMO_GOOGLE_REGISTER_CALLBACK_URL!,
    GOOGLE_LOGIN_CALLBACK_URL: DEV_DEMO_GOOGLE_LOGIN_CALLBACK_URL!,
    FRONTEND_URL: DEV_FRONTEND_URL!,
    PASSWORD_RESET_URL: DEV_PASSWORD_RESET_URL!,
    GOOGLE_AUTH_FAILURE_URL: GOOGLE_AUTH_FAILURE_URL!,
    LOCAL_FOUNDERS_LIST_URL: LOCAL_FOUNDERS_LIST_URL!,
    NOTIFICATION_SERVICE_ROUTE: NOTIFICATION_SERVICE_ROUTE!,
    APP_JWT_SECRET:APP_JWT_SECRET!,
}