"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const dotenv_1 = __importDefault(require("dotenv"));
dotenv_1.default.config();
const { USERS_SERVICE_DEV_DB, FOUNDERS_LIST_DEV_DB, DEV_DEMO_GOOGLE_REGISTER_CALLBACK_URL, DEV_DEMO_GOOGLE_LOGIN_CALLBACK_URL, DEV_FRONTEND_URL, DEV_PASSWORD_RESET_URL, GOOGLE_AUTH_FAILURE_URL, LOCAL_FOUNDERS_LIST_URL, NOTIFICATION_SERVICE_ROUTE, APP_JWT_SECRET, EDEDUN_APP_SECRET, EDEDUN_SMTP_USER_NAME, EDEDUN_SMTP_PASSWORD, EDEDUN_DEV_CLOUDINARY_NAME, EDEDUN_DEV_CLOUDINARY_API_KEY, EDEDUN_DEV_CLOUDINARY_API_SECRET, EDEDUN_DEV_DB, YORUBA_LANGUAGE_PROD_ID } = process.env;
console.log('Running in development mode');
exports.default = {
    FOUNDERS_LIST_DB: FOUNDERS_LIST_DEV_DB,
    USERS_SERVICE_DB: USERS_SERVICE_DEV_DB,
    GOOGLE_REGISTER_CALLBACK_URL: DEV_DEMO_GOOGLE_REGISTER_CALLBACK_URL,
    GOOGLE_LOGIN_CALLBACK_URL: DEV_DEMO_GOOGLE_LOGIN_CALLBACK_URL,
    FRONTEND_URL: DEV_FRONTEND_URL,
    PASSWORD_RESET_URL: DEV_PASSWORD_RESET_URL,
    GOOGLE_AUTH_FAILURE_URL: GOOGLE_AUTH_FAILURE_URL,
    LOCAL_FOUNDERS_LIST_URL: LOCAL_FOUNDERS_LIST_URL,
    NOTIFICATION_SERVICE_ROUTE: NOTIFICATION_SERVICE_ROUTE,
    APP_JWT_SECRET: APP_JWT_SECRET,
    EDEDUN_APP_SECRET: EDEDUN_APP_SECRET,
    EDEDUN_SMTP_USER_NAME: EDEDUN_SMTP_USER_NAME,
    EDEDUN_SMTP_PASSWORD: EDEDUN_SMTP_PASSWORD,
    EDEDUN_CLOUDINARY_NAME: EDEDUN_DEV_CLOUDINARY_NAME,
    EDEDUN_CLOUDINARY_API_KEY: EDEDUN_DEV_CLOUDINARY_API_KEY,
    EDEDUN_CLOUDINARY_API_SECRET: EDEDUN_DEV_CLOUDINARY_API_SECRET,
    EDEDUN_DB: EDEDUN_DEV_DB,
    YORUBA_LANGUAGE_ID: YORUBA_LANGUAGE_PROD_ID
};
