"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("../user-service/src/entities/users.entities");
require("../user-service/src/entities/otp.entities");
require("../lesson-service/src/entities/content");
require("../lesson-service/src/entities/content-file");
require("../lesson-service/src/entities/course");
require("../lesson-service/src/entities/language");
require("../lesson-service/src/entities/lesson");
require("../lesson-service/src/entities/user-course");
require("../lesson-service/src/entities/userDailyGoals");
require("../lesson-service/src/entities/wordForTheDay");
require("../lesson-service/src/entities/quiz");
require("../lesson-service/src/entities/user-quiz");
