import dotenv from 'dotenv'

dotenv.config()

const {
    USERS_SERVICE_PRODUCTION_DB,
    USERS_SERVICE_DEV_DB,
    FOUNDERS_LIST_PRODUCTION_DB,
    PROD_DEMO_GOOGLE_REGISTER_CALLBACK_URL,
    PROD_DEMO_GOOGLE_LOGIN_CALLBACK_URL,
    DEMO_PRODUCTION_FRONTEND_URL,
    PROD_PASSWORD_RESET_URL,
    GOOGLE_AUTH_FAILURE_URL,
    LOCAL_FOUNDERS_LIST_URL,
    NOTIFICATION_SERVICE_ROUTE,
    APP_JWT_SECRET,
    EDEDUN_APP_SECRET,
    EDEDUN_SMTP_USER_NAME,
    EDEDUN_SMTP_PASSWORD,
    EDEDUN_PROD_CLOUDINARY_NAME,
    EDEDUN_PROD_CLOUDINARY_API_KEY,
    EDEDUN_PROD_CLOUDINARY_API_SECRET,
    // EDEDUN_PROD_DB,
    EDEDUN_PROD_DB

} = process.env;

console.log('Running in production mode')

export default {
    FOUNDERS_LIST_DB: FOUNDERS_LIST_PRODUCTION_DB!,
    USERS_SERVICE_DB: USERS_SERVICE_DEV_DB!,
    GOOGLE_REGISTER_CALLBACK_URL: PROD_DEMO_GOOGLE_REGISTER_CALLBACK_URL!,
    GOOGLE_LOGIN_CALLBACK_URL: PROD_DEMO_GOOGLE_LOGIN_CALLBACK_URL!,
    FRONTEND_URL: DEMO_PRODUCTION_FRONTEND_URL!,
    PASSWORD_RESET_URL: PROD_PASSWORD_RESET_URL!,
    GOOGLE_AUTH_FAILURE_URL: GOOGLE_AUTH_FAILURE_URL!,
    LOCAL_FOUNDERS_LIST_URL: LOCAL_FOUNDERS_LIST_URL!,
    NOTIFICATION_SERVICE_ROUTE: NOTIFICATION_SERVICE_ROUTE!,
    APP_JWT_SECRET: APP_JWT_SECRET!,
    EDEDUN_APP_SECRET: EDEDUN_APP_SECRET!,
    EDEDUN_SMTP_USER_NAME: EDEDUN_SMTP_USER_NAME!,
    EDEDUN_SMTP_PASSWORD: EDEDUN_SMTP_PASSWORD!,
    EDEDUN_CLOUDINARY_NAME: EDEDUN_PROD_CLOUDINARY_NAME!,
    EDEDUN_CLOUDINARY_API_KEY: EDEDUN_PROD_CLOUDINARY_API_KEY!,
    EDEDUN_CLOUDINARY_API_SECRET: EDEDUN_PROD_CLOUDINARY_API_SECRET!,
    EDEDUN_DB: EDEDUN_PROD_DB!,
}